# Generated by Django 5.1.2 on 2024-11-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_cal_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
