# Generated by Django 5.1.2 on 2024-11-05 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memoset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_memo_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="memo",
            name="memo_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_memo",
                to="memos.memoset",
            ),
        ),
        migrations.AddConstraint(
            model_name="memoset",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_user_title"
            ),
        ),
    ]
