# Generated by Django 5.1.3 on 2024-12-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="memo_set",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_memo",
                to="memos.memoset",
            ),
        ),
    ]
