# Generated by Django 5.1.4 on 2024-12-14 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0003_alter_memo_memo_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="memo_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_memo",
                to="memos.memoset",
            ),
        ),
    ]
