# Generated by Django 5.1.3 on 2024-11-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_repeat",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
