# Generated by Django 5.1.2 on 2024-11-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="google_url",
        ),
    ]
