# Generated by Django 5.1.3 on 2024-12-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0004_alter_schedule_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="calendar",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_schedule",
                to="calendars.calendar",
            ),
        ),
    ]
