# Generated by Django 5.1.3 on 2024-11-23 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0002_initial"),
        ("todos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="memo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memo_todo",
                to="memos.memo",
            ),
        ),
    ]
