# Generated by Django 5.1.4 on 2024-12-14 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_subtodo_memo_alter_todo_todo_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="todo_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_todo",
                to="todos.todoset",
            ),
        ),
    ]
