# Generated by Django 5.1.2 on 2024-11-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="todo",
            field=models.ManyToManyField(related_name="todo_tags", to="todos.todo"),
        ),
    ]
